# Generated by Django 4.2.25 on 2025-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_attachment_message_reply_to_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
