# Generated by Django 4.2.25 on 2025-10-31 11:51

import django.core.validators
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_message_edited_message_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to=forum.models.forum_attachment_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "bmp",
                            "svg",
                            "mp4",
                            "webm",
                            "ogg",
                            "mov",
                            "mkv",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "txt",
                            "zip",
                            "rar",
                            "7z",
                        ]
                    )
                ],
            ),
        ),
    ]
