# Generated by Django 4.2.23 on 2025-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
