# Generated by Django 4.2.23 on 2025-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_orderitem_quantity_alter_orderitem_pack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
