# Generated by Django 4.2.23 on 2025-08-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_order_stripe_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_session_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("MOBILEMONEY", "Mobile Money"),
                    ("STRIPE", "Carte bancaire (Stripe)"),
                ],
                default="MOBILEMONEY",
                max_length=20,
            ),
        ),
    ]
