# Generated by Django 4.2.23 on 2025-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_remove_order_stripe_session_id_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="ID de la session Stripe Checkout",
                max_length=255,
                null=True,
            ),
        ),
    ]
