# Generated by Django 4.2.23 on 2025-09-05 05:29

import django.core.validators
from django.db import migrations, models
import exams.models
import exams.storages


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Extrait Épreuve + Corrigé", max_length=150
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Fichier .zip (max ~500Mo, contrôles anti zip-bomb).",
                        upload_to="free_samples/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["zip"]),
                            exams.models.validate_zip,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AlterField(
            model_name="pack",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=exams.storages.ProtectedStorage(),
                upload_to="packs/",
                validators=[
                    django.core.validators.FileExtensionValidator(["zip"]),
                    exams.models.validate_zip,
                ],
            ),
        ),
    ]
